# Path to your oh-my-zsh configuration.
CONF=$HOME/dotfiles/zsh
ZSH=$HOME/.oh-my-zsh

source $CONF/aliases
source $CONF/functions/general
source $CONF/functions/aws
source $CONF/functions/bbc
source $CONF/functions/db
source $CONF/functions/git

TZ="Europe/London"
HISTFILE=$HOME/.zhistory
HISTSIZE=20000
SAVEHIST=20000

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(aws brew bower docker git github go npm osx ruby rails sbt scala vagrant)

source $ZSH/oh-my-zsh.sh
source $CONF/zshenv
source $CONF/prompt

export PATH=$PATH:$HOME/bin:$HOME/.rbenv/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin
eval "$(rbenv init - zsh)"

# better cding
# http://robots.thoughtbot.com/cding-to-frequently-used-directories-in-zsh
setopt auto_cd
cdpath=($HOME/projects $HOME/xcode)
